@url = http://localhost:8000/api
@school_id = 1

# @name successLogin
GET {{ url }}/login?contact=9999999999&prn=DEM/0003/2122 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name successLogin2
GET {{ url }}/login?contact=8989056890&prn=DEM/0001/2122 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name logout
GET {{ url }}/logout/1/8989056890 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name failedLogin
GET {{ url }}/login?contact=8989056890&prn=WLS/0010/2021 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getAttendance
GET {{ url }}/attendances/1 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getClasswork
GET {{ url }}/classwork/1?school_id={{school_id}} HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getFees
GET {{ url }}/fees/1?school_id={{school_id}} HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getVersion
GET {{ url }}/version HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getHomework
GET {{ url }}/homework/3?school_id={{school_id}} HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getHoliday
GET {{ url }}/holidays?school_id={{school_id}} HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getGallery
GET {{ url }}/gallery/4?school_id={{school_id}} HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getNotice
GET {{ url }}/notices/3?school_id={{school_id}} HTTP/1.1
Accept: application/json
IsApi: true
###


# @name getChats
GET {{ url }}/chats/?teacher=5&student=1 HTTP/1.1
Accept: application/json
UniqueIdentity: true
###

# @name getObservation
GET {{ url }}/observations/1?school_id={{school_id}} HTTP/1.1
Accept: application/json
IsApi: true
###


##########  LIVE TESTS  ############

# @name liveLogin
GET https://wonderlearning.in/api/login?contact=7264809024&prn=DEM/0006/2122 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name liveLogout
GET https://wonderlearning.in/api/logout/11/7264809024 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getLiveAttendance
GET https://wonderlearning.in/api/attendances/13 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getLiveClasswork
GET https://wonderlearning.in/api/classwork/13?school_id=2 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getLiveFees
GET https://wonderlearning.in/api/fees/8?school_id=2 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getLiveHomework
GET https://wonderlearning.in/api/homework/8?school_id=2 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getLiveVersion
GET https://wonderlearning.in/api/version HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getLiveHoliday
GET https://wonderlearning.in/api/holidays?school_id=2 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getLiveGallery
GET https://wonderlearning.in/api/gallery/6?school_id=3 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getLiveNotice
GET  https://wonderlearning.in/api/notices/6?school_id=3 HTTP/1.1
Accept: application/json
IsApi: true
###
