@url = http://localhost:8000/api
@school_id = 1

# @name successLogin
GET {{ url }}/login?contact=9999999999&prn=DEM/0003/2122 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name successLogin2
GET {{ url }}/login?contact=8989056890&prn=DEM/0001/2122 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name logout
GET {{ url }}/logout/1/9999999999 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name failedLogin
GET {{ url }}/login?contact=8989056890&prn=WLS/0010/2021 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getAttendance
GET {{ url }}/attendances/7 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getClasswork
GET {{ url }}/classwork/1?school_id={{school_id}} HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getFees
GET {{ url }}/fees/1?school_id={{school_id}} HTTP/1.1
Accept: application/json
IsApi: true
###

# @name liveLogin
GET https://wonderlearning.in/api/login?contact=9090909090&prn=TSS/0002/2122 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name logout
GET https://wonderlearning.in/api/logout/8/9090909090 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getLiveAttendance
GET https://wonderlearning.in/api/attendances/8 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getLiveClasswork
GET https://wonderlearning.in/api/classwork/8?school_id=2 HTTP/1.1
Accept: application/json
IsApi: true
###

# @name getLiveFees
GET https://wonderlearning.in/api/fees/8?school_id=2 HTTP/1.1
Accept: application/json
IsApi: true
##