@url = http://localhost:8000
@school_id = 1

# @name successLogin
GET {{ url }}/api/login?contact=9999999999&prn=DEM/0003/2122 HTTP/1.1
Accept: application/json
###

# @name successLogin2
GET {{ url }}/api/login?contact=8989056890&prn=DEM/0001/2122 HTTP/1.1
Accept: application/json
###

# @name failedLogin
GET {{ url }}/api/login?contact=8989056890&prn=WLS/0010/2021 HTTP/1.1
Accept: application/json
###